server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql//192.168.239.129:3306/test
    username: root
    password: 000000
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    
    init
    #filters: stat

